# Generated by Django 5.2.16 on 2026-07-31 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='nom')),
                ('first_name', models.CharField(max_length=100, verbose_name='prénom')),
                ('date_of_birth', models.DateField(verbose_name='date de naissance')),
                ('gender', models.CharField(choices=[('M', 'Garçon'), ('F', 'Fille')], max_length=1, verbose_name='sexe')),
                ('enrollment_date', models.DateField(verbose_name="date d'inscription")),
                ('status', models.CharField(choices=[('ACTIVE', 'Actif'), ('ARCHIVED', 'Archivé')], default='ACTIVE', max_length=10, verbose_name='statut')),
                ('archived_at', models.DateTimeField(blank=True, null=True, verbose_name='archivé le')),
                ('archive_reason', models.CharField(blank=True, max_length=255, verbose_name="motif d'archivage")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
    ]
