# Generated by Django 5.2.16 on 2026-08-09 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cabinet',
            field=models.CharField(blank=True, max_length=50, verbose_name='armoire'),
        ),
        migrations.AddField(
            model_name='student',
            name='drawer',
            field=models.CharField(blank=True, max_length=50, verbose_name='tiroir'),
        ),
        migrations.AddField(
            model_name='student',
            name='file_number',
            field=models.CharField(blank=True, editable=False, max_length=12, unique=True, verbose_name='numéro de dossier'),
        ),
        migrations.AddField(
            model_name='student',
            name='position',
            field=models.CharField(blank=True, max_length=50, verbose_name='position'),
        ),
        migrations.AddField(
            model_name='student',
            name='registration_grade',
            field=models.CharField(choices=[('PS', 'Petite Section'), ('MS', 'Moyenne Section'), ('GS', 'Grande Section')], default='PS', max_length=2, verbose_name="niveau à l'inscription"),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='FileNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(verbose_name='année')),
                ('grade', models.CharField(choices=[('PS', 'Petite Section'), ('MS', 'Moyenne Section'), ('GS', 'Grande Section')], max_length=2, verbose_name='niveau')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='dernier numéro')),
            ],
            options={
                'verbose_name': 'séquence de numéro de dossier',
                'verbose_name_plural': 'séquences de numéro de dossier',
                'constraints': [models.UniqueConstraint(fields=('year', 'grade'), name='unique_file_number_sequence')],
            },
        ),
    ]
