# Generated by Django 5.2.16 on 2026-08-18 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(max_length=100, verbose_name='domaine')),
                ('period', models.CharField(max_length=50, verbose_name='période')),
                ('scale', models.CharField(blank=True, choices=[('EXCELLENT', 'Excellent'), ('TRES_BIEN', 'Très bien'), ('BIEN', 'Bien'), ('EN_DEVELOPPEMENT', 'En développement'), ('BESOIN_DE_SOUTIEN', 'Besoin de soutien')], max_length=20, verbose_name='appréciation')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='note')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='remarque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='academics.enrollment')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_recorded', to=settings.AUTH_USER_MODEL, verbose_name='enregistré par')),
            ],
            options={
                'verbose_name': 'évaluation',
                'verbose_name_plural': 'évaluations',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'domain', 'period'), name='unique_assessment_per_enrollment_domain_period'), models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='assessment_score_non_negative')],
            },
        ),
    ]
