# Generated by Django 5.2.16 on 2026-08-18 14:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0002_staff_hire_date_staff_is_active_staff_position'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='montant')),
                ('date', models.DateField(verbose_name='date')),
                ('period', models.CharField(help_text='ex. Janvier 2026', max_length=20, verbose_name='période')),
                ('method', models.CharField(choices=[('ESPECES', 'Espèces'), ('VIREMENT', 'Virement bancaire'), ('CHEQUE', 'Chèque'), ('MOBILE_MONEY', 'Mobile money')], max_length=20, verbose_name='moyen de paiement')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='remarque')),
                ('is_voided', models.BooleanField(default=False, verbose_name='annulé')),
                ('void_reason', models.CharField(blank=True, max_length=255, verbose_name="motif d'annulation")),
                ('voided_at', models.DateTimeField(blank=True, null=True, verbose_name='annulé le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payments_recorded', to=settings.AUTH_USER_MODEL, verbose_name='enregistré par')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='salary_payments', to='staff.staff')),
                ('voided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='salary_payments_voided', to=settings.AUTH_USER_MODEL, verbose_name='annulé par')),
            ],
            options={
                'verbose_name': 'paiement de salaire',
                'verbose_name_plural': 'paiements de salaire',
                'ordering': ['-date', '-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='salary_payment_amount_positive')],
            },
        ),
    ]
