# Generated by Django 5.2.16 on 2026-08-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('CREATE', 'Création'), ('UPDATE', 'Modification'), ('ARCHIVE', 'Archivage'), ('REACTIVATE', 'Réactivation'), ('DEACTIVATE', 'Désactivation'), ('DELETE', 'Suppression'), ('VOID', 'Annulation')], max_length=20),
        ),
    ]
