# Generated by Django 5.2.16 on 2026-08-18 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('guardians', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='remarque')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('authorized_person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickups', to='guardians.authorizedpickupperson', verbose_name='personne autorisée')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pickups', to='academics.enrollment')),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pickups', to='guardians.guardian', verbose_name='tuteur')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickups_recorded', to=settings.AUTH_USER_MODEL, verbose_name='enregistré par')),
            ],
            options={
                'verbose_name': 'départ',
                'verbose_name_plural': 'départs',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('enrollment', 'date'), name='unique_pickup_per_enrollment_date'), models.CheckConstraint(condition=models.Q(models.Q(('authorized_person__isnull', True), ('guardian__isnull', False)), models.Q(('authorized_person__isnull', False), ('guardian__isnull', True)), _connector='OR'), name='pickup_exactly_one_person')],
            },
        ),
    ]
