# Generated by Django 5.2.16 on 2026-08-09 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('staff', '0001_initial'),
        ('students', '0002_student_cabinet_student_drawer_student_file_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=9, unique=True, verbose_name='année scolaire')),
                ('start_date', models.DateField(verbose_name='date de début')),
                ('end_date', models.DateField(verbose_name='date de fin')),
                ('is_current', models.BooleanField(default=False, verbose_name='année courante')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'année scolaire',
                'verbose_name_plural': 'années scolaires',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('PS', 'Petite Section'), ('MS', 'Moyenne Section'), ('GS', 'Grande Section')], max_length=2, verbose_name='niveau')),
                ('name', models.CharField(blank=True, max_length=20, verbose_name='nom de la classe')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='staff.staff', verbose_name='enseignant')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='academics.schoolyear')),
            ],
            options={
                'verbose_name': 'classe',
                'verbose_name_plural': 'classes',
                'ordering': ['school_year', 'grade', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(choices=[('PS', 'Petite Section'), ('MS', 'Moyenne Section'), ('GS', 'Grande Section')], max_length=2, verbose_name='niveau')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('WITHDRAWN', 'Retirée')], default='ACTIVE', max_length=10, verbose_name='statut')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='retirée le')),
                ('withdrawal_reason', models.CharField(blank=True, max_length=255, verbose_name='motif de retrait')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='enrollments', to='academics.class', verbose_name='classe')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='students.student')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.schoolyear')),
            ],
            options={
                'verbose_name': 'inscription',
                'verbose_name_plural': 'inscriptions',
                'ordering': ['-school_year__start_date'],
                'constraints': [models.UniqueConstraint(fields=('student', 'school_year'), name='unique_enrollment_per_student_year')],
            },
        ),
        migrations.AddConstraint(
            model_name='class',
            constraint=models.UniqueConstraint(fields=('school_year', 'grade', 'name'), name='unique_class_per_year_grade_name'),
        ),
    ]
